import "server-only";
// Generated by scripts/prepare-content.mjs. Do not edit manually.
import startersWriting from "@data/writing/starters.json";
import moversWriting from "@data/writing/movers.json";
import flyersWriting from "@data/writing/flyers.json";
import ketWriting from "@data/writing/ket.json";
import petWriting from "@data/writing/pet.json";

export const writingDocuments = [startersWriting, moversWriting, flyersWriting, ketWriting, petWriting];
