import "server-only";
// Generated by scripts/prepare-content.mjs. Do not edit manually.
import startersListening from "@data/listening/starters.json";
import moversListening from "@data/listening/movers.json";
import flyersListening from "@data/listening/flyers.json";
import ketListening from "@data/listening/ket.json";
import petListening from "@data/listening/pet.json";

export const listeningDocuments = [startersListening, moversListening, flyersListening, ketListening, petListening];
