import { cp, lstat, mkdir, readdir, readlink, rm, symlink, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const appDirectory = join(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryDirectory = join(appDirectory, "..");
const dataDirectory = join(repositoryDirectory, "tinysteps-data");
const contentDirectory = join(appDirectory, ".content");
const levels = ["starters", "movers", "flyers", "ket", "pet"];
const expectedLessons = { starters: 30, movers: 30, flyers: 40, ket: 35, pet: 40 };

await rm(contentDirectory, { force: true, recursive: true });
await mkdir(contentDirectory, { recursive: true });
for (const source of ["vocabulary", "topics", "audio"]) {
  await cp(join(dataDirectory, source), join(contentDirectory, source), { recursive: true, filter: (path) => !path.endsWith(".mp3") });
}

// Dev-only: serve MP3s straight from tinysteps-data via a public/audio symlink, so
// audioUrl()'s relative "/audio/..." path (used whenever NEXT_PUBLIC_AUDIO_BASE_URL is
// unset) resolves locally. Skipped on Vercel — prod audio comes from Supabase Storage
// (phase 07), and tracing 150MB of MP3s into the build output would be wasteful/wrong.
if (!process.env.VERCEL) {
  const audioTarget = join(dataDirectory, "audio");
  const publicAudio = join(appDirectory, "public", "audio");
  let needsLink = true;
  try {
    const stat = await lstat(publicAudio);
    if (stat.isSymbolicLink() && (await readlink(publicAudio)) === audioTarget) {
      needsLink = false;
    } else {
      await rm(publicAudio, { force: true, recursive: true });
    }
  } catch {
    // Nothing at publicAudio yet — fine, we'll create it below.
  }
  if (needsLink) {
    await symlink(audioTarget, publicAudio, "dir");
  }
} else {
  console.log("Skipping public/audio symlink on Vercel — audio served from Storage.");
}

const imports = [];
for (const level of levels) {
  const sourceDirectory = join(dataDirectory, "lessons", level);
  const files = (await readdir(sourceDirectory)).filter((file) => /^lesson-\d{3}\.json$/.test(file)).sort();
  if (files.length !== expectedLessons[level]) throw new Error(`${level}: expected ${expectedLessons[level]} lessons, found ${files.length}`);
  for (const file of files) {
    const source = join(sourceDirectory, file);
    const target = join(contentDirectory, "lessons", level, file);
    await mkdir(dirname(target), { recursive: true });
    await cp(source, target);
    const name = `${level}${file.replace(/[^a-zA-Z0-9]/g, "")}`;
    imports.push({ name, path: `@data/${relative(contentDirectory, target).replaceAll("\\", "/")}` });
  }
}

const indexSource = [
  'import "server-only";',
  "// Generated by scripts/prepare-content.mjs. Do not edit manually.",
  ...imports.map(({ name, path }) => `import ${name} from "${path}";`),
  "", `export const lessonDocuments = [${imports.map(({ name }) => name).join(", ")}];`, "",
].join("\n");
await writeFile(join(appDirectory, "lib", "content", "generated-lessons-index.ts"), indexSource);
console.log(`Prepared private content: 5 vocab files, ${imports.length} lessons, topics, and manifest.`);