#!/usr/bin/env python3
"""
topup_vocabulary_batch2.py
Second batch of vocabulary entries. Compact format: (word, pos, ipa, topic_id)
image_hint and example_sentence are auto-generated from templates.
"""

import json, os, re, random

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
VOCAB_DIR  = os.path.join(SCRIPT_DIR, "vocabulary")
TOPICS_FILE = os.path.join(SCRIPT_DIR, "topics", "topics.json")
LEVELS     = ["starters", "movers", "flyers", "ket", "pet"]
TARGETS    = {"starters": 300, "movers": 400, "flyers": 500, "ket": 400, "pet": 500}

# ── auto-generate helpers ──────────────────────────────────────────────────

EXAMPLE_TMPL = {
    "starters": {
        "noun":      ["I see {w}.", "This is {w}.", "I have {w}.", "Look at {w}."],
        "verb":      ["Please {w}.", "I {w} now.", "We {w} here.", "{w}, please."],
        "adjective": ["It is {w}.", "He is {w}.", "That is {w}.", "It looks {w}."],
        "adverb":    ["{w}, please.", "Do it {w}.", "Walk {w}."],
        "interjection": ["{w}!", "Say {w}.", "I say {w}."],
        "phrase":    ["I say {w}.", "We use {w}."],
        "default":   ["I like {w}.", "This is {w}."],
    },
    "movers": {
        "noun":      ["I bought {w} yesterday.", "She has a {w}.", "Can you find the {w}?", "I need {w}."],
        "verb":      ["I want to {w} today.", "Can you {w} with me?", "She {w}ed yesterday.", "He can {w} well."],
        "adjective": ["It was very {w}.", "She looks {w}.", "The weather is {w}.", "He was so {w}."],
        "adverb":    ["She walked {w}.", "Do it {w}.", "He answered {w}."],
        "interjection": ["{w}!", "She said {w}.", "He shouted {w}."],
        "default":   ["She used {w} yesterday.", "I have {w} now."],
    },
    "flyers": {
        "noun":      ["I have already prepared the {w}.", "You should check the {w}.", "She brought the {w}."],
        "verb":      ["You should {w} carefully.", "I am going to {w}.", "She has already {w}ed."],
        "adjective": ["The lesson was so {w}.", "He is such a {w} student.", "It is too {w}."],
        "adverb":    ["She finished {w}.", "He answered the question {w}."],
        "default":   ["I have already seen the {w}.", "You must check the {w}."],
    },
    "ket": {
        "noun":      ["I'd like to confirm the {w}.", "Could you check the {w}?", "The {w} has been updated."],
        "verb":      ["Could you {w} this for me?", "I used to {w} every day.", "I have been {w}ing since Monday."],
        "adjective": ["The report is so {w}.", "He is such a {w} colleague.", "It was {w} enough."],
        "default":   ["I'd like to discuss the {w}.", "Could we review the {w}?"],
    },
    "pet": {
        "noun":      ["If I had a better {w}, I would use it.", "The {w} should be confirmed by Friday."],
        "verb":      ["If I had time, I would {w} more.", "I wish I could {w} better."],
        "adjective": ["If it were {w}, I would agree.", "She said that it was {w}."],
        "default":   ["Furthermore, the {w} was discussed.", "I apologise for the {w} issue."],
    },
}

IMAGE_TMPL = {
    "noun":      "a clear image showing {w} in context",
    "verb":      "a person performing the action of {w}",
    "adjective": "an image clearly illustrating the quality {w}",
    "adverb":    "an image showing someone doing something {w}",
    "interjection": "a speech bubble showing the expression {w}",
    "phrase":    "a speech bubble with the phrase {w}",
    "default":   "a simple visual representation of {w}",
}

def make_example(word, pos, level):
    pool = EXAMPLE_TMPL.get(level, EXAMPLE_TMPL["movers"])
    tmpl_list = pool.get(pos, pool.get("default", ["I see {w}."]))
    tmpl = random.choice(tmpl_list)
    return tmpl.replace("{w}", word)

def make_hint(word, pos):
    tmpl = IMAGE_TMPL.get(pos, IMAGE_TMPL["default"])
    return tmpl.replace("{w}", word)

# ── Compact word banks ─────────────────────────────────────────────────────
# Format: (word, pos, ipa, topic_id)

BATCH2 = {

"starters": [
    # topic_before_class
    ("key", "noun", "/kiː/", "topic_before_class"),
    ("hall", "noun", "/hɔːl/", "topic_before_class"),
    ("clean", "verb", "/kliːn/", "topic_before_class"),
    ("tidy", "adjective", "/ˈtaɪ.di/", "topic_before_class"),
    ("shine", "verb", "/ʃaɪn/", "topic_before_class"),
    ("space", "noun", "/speɪs/", "topic_before_class"),
    ("wall", "noun", "/wɔːl/", "topic_before_class"),
    ("floor", "noun", "/flɔːr/", "topic_before_class"),
    ("light", "noun", "/laɪt/", "topic_before_class"),
    # topic_in_class
    ("pencil", "noun", "/ˈpen.sɪl/", "topic_in_class"),
    ("eraser", "noun", "/ɪˈreɪ.zər/", "topic_in_class"),
    ("ruler", "noun", "/ˈruː.lər/", "topic_in_class"),
    ("chalk", "noun", "/tʃɔːk/", "topic_in_class"),
    ("map", "noun", "/mæp/", "topic_in_class"),
    ("computer", "noun", "/kəmˈpjuː.tər/", "topic_in_class"),
    ("game", "noun", "/ɡeɪm/", "topic_in_class"),
    ("quiz", "noun", "/kwɪz/", "topic_in_class"),
    ("test", "noun", "/test/", "topic_in_class"),
    ("page", "noun", "/peɪdʒ/", "topic_in_class"),
    ("read", "verb", "/riːd/", "topic_in_class"),
    # topic_giving_instructions
    ("count", "verb", "/kaʊnt/", "topic_giving_instructions"),
    ("cut", "verb", "/kʌt/", "topic_giving_instructions"),
    ("paste", "verb", "/peɪst/", "topic_giving_instructions"),
    ("colour", "verb", "/ˈkʌl.ər/", "topic_giving_instructions"),
    ("underline", "verb", "/ˌʌn.dəˈlaɪn/", "topic_giving_instructions"),
    ("cross", "verb", "/krɒs/", "topic_giving_instructions"),
    # topic_checking_understanding
    ("listen", "verb", "/ˈlɪs.ən/", "topic_checking_understanding"),
    ("repeat", "verb", "/rɪˈpiːt/", "topic_checking_understanding"),
    ("check", "verb", "/tʃek/", "topic_checking_understanding"),
    ("understand", "verb", "/ˌʌn.dəˈstænd/", "topic_checking_understanding"),
    # topic_praise_correction
    ("great", "adjective", "/ɡreɪt/", "topic_praise_correction"),
    ("excellent", "adjective", "/ˈek.səl.ənt/", "topic_praise_correction"),
    ("perfect", "adjective", "/ˈpɜː.fekt/", "topic_praise_correction"),
    ("wonderful", "adjective", "/ˈwʌn.də.fəl/", "topic_praise_correction"),
    ("reward", "noun", "/rɪˈwɔːd/", "topic_praise_correction"),
    # topic_school_communication
    ("report", "noun", "/rɪˈpɔːt/", "topic_school_communication"),
    ("form", "noun", "/fɔːm/", "topic_school_communication"),
    ("sign", "verb", "/saɪn/", "topic_school_communication"),
    ("date", "noun", "/deɪt/", "topic_school_communication"),
    # topic_market
    ("orange", "noun", "/ˈɒr.ɪndʒ/", "topic_market"),
    ("strawberry", "noun", "/ˈstrɔː.bər.i/", "topic_market"),
    ("corn", "noun", "/kɔːn/", "topic_market"),
    ("peanut", "noun", "/ˈpiː.nʌt/", "topic_market"),
    ("cucumber", "noun", "/ˈkjuː.kʌm.bər/", "topic_market"),
    ("cabbage", "noun", "/ˈkæb.ɪdʒ/", "topic_market"),
    # topic_restaurant
    ("coffee", "noun", "/ˈkɒf.i/", "topic_restaurant"),
    ("juice", "noun", "/dʒuːs/", "topic_restaurant"),
    ("cake", "noun", "/keɪk/", "topic_restaurant"),
    ("ice", "noun", "/aɪs/", "topic_restaurant"),
    ("fork", "noun", "/fɔːk/", "topic_restaurant"),
    ("spoon", "noun", "/spuːn/", "topic_restaurant"),
    ("chopsticks", "noun", "/ˈtʃɒp.stɪks/", "topic_restaurant"),
    ("bowl", "noun", "/bəʊl/", "topic_restaurant"),
    ("plate", "noun", "/pleɪt/", "topic_restaurant"),
    # topic_travel
    ("boat", "noun", "/bəʊt/", "topic_travel"),
    ("ticket", "noun", "/ˈtɪk.ɪt/", "topic_travel"),
    ("street", "noun", "/striːt/", "topic_travel"),
    ("bridge", "noun", "/brɪdʒ/", "topic_travel"),
    ("park", "noun", "/pɑːk/", "topic_travel"),
    # topic_phone
    ("text", "noun", "/tekst/", "topic_phone"),
    ("screen", "noun", "/skriːn/", "topic_phone"),
    ("call", "noun", "/kɔːl/", "topic_phone"),
    # topic_health
    ("cough", "verb", "/kɒf/", "topic_health"),
    ("sneeze", "verb", "/sniːz/", "topic_health"),
    ("bandage", "noun", "/ˈbæn.dɪdʒ/", "topic_health"),
    ("tablet", "noun", "/ˈtæb.lɪt/", "topic_health"),
    ("hospital", "noun", "/ˈhɒs.pɪ.təl/", "topic_health"),
    # topic_social
    ("age", "noun", "/eɪdʒ/", "topic_social"),
    ("birthday", "noun", "/ˈbɜːθ.deɪ/", "topic_social"),
    ("present", "noun", "/ˈprez.ənt/", "topic_social"),
    ("party", "noun", "/ˈpɑː.ti/", "topic_social"),
    ("game", "noun", "/ɡeɪm/", "topic_social"),
    ("pet", "noun", "/pet/", "topic_social"),
    ("cat", "noun", "/kæt/", "topic_social"),
    ("dog", "noun", "/dɒɡ/", "topic_social"),
    ("funny", "adjective", "/ˈfʌn.i/", "topic_social"),
    ("kind", "adjective", "/kaɪnd/", "topic_social"),
    ("tall", "adjective", "/tɔːl/", "topic_social"),
    ("short", "adjective", "/ʃɔːt/", "topic_social"),
    ("fast", "adjective", "/fɑːst/", "topic_social"),
    ("slow", "adjective", "/sləʊ/", "topic_social"),
    ("long", "adjective", "/lɒŋ/", "topic_social"),
],

"movers": [
    # topic_before_class
    ("assignment", "noun", "/əˈsaɪn.mənt/", "topic_before_class"),
    ("checklist", "noun", "/ˈtʃek.lɪst/", "topic_before_class"),
    ("supply", "noun", "/səˈplaɪ/", "topic_before_class"),
    ("schedule", "noun", "/ˈʃed.juːl/", "topic_before_class"),
    ("attend", "verb", "/əˈtend/", "topic_before_class"),
    ("set", "verb", "/set/", "topic_before_class"),
    ("hang", "verb", "/hæŋ/", "topic_before_class"),
    ("arrange", "verb", "/əˈreɪndʒ/", "topic_before_class"),
    ("pack", "verb", "/pæk/", "topic_before_class"),
    ("collect", "verb", "/kəˈlekt/", "topic_before_class"),
    ("clean", "adjective", "/kliːn/", "topic_before_class"),
    ("ready", "adjective", "/ˈred.i/", "topic_before_class"),
    ("busy", "adjective", "/ˈbɪz.i/", "topic_before_class"),
    ("finished", "adjective", "/ˈfɪn.ɪʃt/", "topic_before_class"),
    ("notebook", "noun", "/ˈnəʊt.bʊk/", "topic_before_class"),
    ("textbook", "noun", "/ˈtekst.bʊk/", "topic_before_class"),
    ("label", "noun", "/ˈleɪ.bəl/", "topic_before_class"),
    # topic_in_class
    ("project", "noun", "/ˈprɒdʒ.ekt/", "topic_in_class"),
    ("poster", "noun", "/ˈpəʊ.stər/", "topic_in_class"),
    ("report", "noun", "/rɪˈpɔːt/", "topic_in_class"),
    ("essay", "noun", "/ˈes.eɪ/", "topic_in_class"),
    ("note", "noun", "/nəʊt/", "topic_in_class"),
    ("page", "noun", "/peɪdʒ/", "topic_in_class"),
    ("chapter", "noun", "/ˈtʃæp.tər/", "topic_in_class"),
    ("paragraph", "noun", "/ˈpær.ə.ɡrɑːf/", "topic_in_class"),
    ("word", "noun", "/wɜːd/", "topic_in_class"),
    ("spelling", "noun", "/ˈspel.ɪŋ/", "topic_in_class"),
    ("grammar", "noun", "/ˈɡræm.ər/", "topic_in_class"),
    ("point", "noun", "/pɔɪnt/", "topic_in_class"),
    ("topic", "noun", "/ˈtɒp.ɪk/", "topic_in_class"),
    ("subject", "noun", "/ˈsʌb.dʒekt/", "topic_in_class"),
    ("class", "noun", "/klɑːs/", "topic_in_class"),
    ("level", "noun", "/ˈlev.əl/", "topic_in_class"),
    ("skill", "noun", "/skɪl/", "topic_in_class"),
    ("step", "noun", "/step/", "topic_in_class"),
    ("ask", "verb", "/ɑːsk/", "topic_in_class"),
    ("show", "verb", "/ʃəʊ/", "topic_in_class"),
    ("write", "verb", "/raɪt/", "topic_in_class"),
    ("listen", "verb", "/ˈlɪs.ən/", "topic_in_class"),
    ("speak", "verb", "/spiːk/", "topic_in_class"),
    ("read", "verb", "/riːd/", "topic_in_class"),
    ("check", "verb", "/tʃek/", "topic_in_class"),
    ("use", "verb", "/juːz/", "topic_in_class"),
    ("choose", "verb", "/tʃuːz/", "topic_in_class"),
    ("share", "verb", "/ʃeər/", "topic_in_class"),
    ("raise", "verb", "/reɪz/", "topic_in_class"),
    ("clap", "verb", "/klæp/", "topic_in_class"),
    ("point", "verb", "/pɔɪnt/", "topic_in_class"),
    # topic_giving_instructions
    ("form", "noun", "/fɔːm/", "topic_giving_instructions"),
    ("line", "noun", "/laɪn/", "topic_giving_instructions"),
    ("box", "noun", "/bɒks/", "topic_giving_instructions"),
    ("row", "noun", "/rəʊ/", "topic_giving_instructions"),
    ("column", "noun", "/ˈkɒl.əm/", "topic_giving_instructions"),
    ("blank", "noun", "/blæŋk/", "topic_giving_instructions"),
    ("space", "noun", "/speɪs/", "topic_giving_instructions"),
    ("direction", "noun", "/daɪˈrek.ʃən/", "topic_giving_instructions"),
    ("finish", "verb", "/ˈfɪn.ɪʃ/", "topic_giving_instructions"),
    ("start", "verb", "/stɑːt/", "topic_giving_instructions"),
    ("begin", "verb", "/bɪˈɡɪn/", "topic_giving_instructions"),
    ("stop", "verb", "/stɒp/", "topic_giving_instructions"),
    ("continue", "verb", "/kənˈtɪn.juː/", "topic_giving_instructions"),
    ("swap", "verb", "/swɒp/", "topic_giving_instructions"),
    ("take", "verb", "/teɪk/", "topic_giving_instructions"),
    ("pass", "verb", "/pɑːs/", "topic_giving_instructions"),
    ("give", "verb", "/ɡɪv/", "topic_giving_instructions"),
    ("return", "verb", "/rɪˈtɜːn/", "topic_giving_instructions"),
    ("try", "verb", "/traɪ/", "topic_giving_instructions"),
    ("keep", "verb", "/kiːp/", "topic_giving_instructions"),
    # topic_checking_understanding
    ("answer", "verb", "/ˈɑːn.sər/", "topic_checking_understanding"),
    ("question", "noun", "/ˈkwes.tʃən/", "topic_checking_understanding"),
    ("guess", "verb", "/ɡes/", "topic_checking_understanding"),
    ("explain", "verb", "/ɪkˈspleɪn/", "topic_checking_understanding"),
    ("describe", "verb", "/dɪˈskraɪb/", "topic_checking_understanding"),
    ("tell", "verb", "/tel/", "topic_checking_understanding"),
    ("know", "verb", "/nəʊ/", "topic_checking_understanding"),
    ("think", "verb", "/θɪŋk/", "topic_checking_understanding"),
    ("remember", "verb", "/rɪˈmem.bər/", "topic_checking_understanding"),
    ("forget", "verb", "/fəˈɡet/", "topic_checking_understanding"),
    ("find", "verb", "/faɪnd/", "topic_checking_understanding"),
    ("notice", "verb", "/ˈnəʊ.tɪs/", "topic_checking_understanding"),
    # topic_praise_correction
    ("mark", "verb", "/mɑːk/", "topic_praise_correction"),
    ("grade", "verb", "/ɡreɪd/", "topic_praise_correction"),
    ("score", "verb", "/skɔːr/", "topic_praise_correction"),
    ("pass", "verb", "/pɑːs/", "topic_praise_correction"),
    ("fail", "verb", "/feɪl/", "topic_praise_correction"),
    ("redo", "verb", "/ˌriːˈduː/", "topic_praise_correction"),
    ("fix", "verb", "/fɪks/", "topic_praise_correction"),
    ("neat", "adjective", "/niːt/", "topic_praise_correction"),
    ("clear", "adjective", "/klɪər/", "topic_praise_correction"),
    ("quick", "adjective", "/kwɪk/", "topic_praise_correction"),
    ("hard", "adjective", "/hɑːd/", "topic_praise_correction"),
    # topic_school_communication
    ("phone", "verb", "/fəʊn/", "topic_school_communication"),
    ("write", "verb", "/raɪt/", "topic_school_communication"),
    ("send", "verb", "/send/", "topic_school_communication"),
    ("receive", "verb", "/rɪˈsiːv/", "topic_school_communication"),
    ("invite", "verb", "/ɪnˈvaɪt/", "topic_school_communication"),
    ("inform", "verb", "/ɪnˈfɔːm/", "topic_school_communication"),
    ("arrive", "verb", "/əˈraɪv/", "topic_school_communication"),
    ("leave", "verb", "/liːv/", "topic_school_communication"),
    ("visit", "verb", "/ˈvɪz.ɪt/", "topic_school_communication"),
    ("bring", "verb", "/brɪŋ/", "topic_school_communication"),
    ("take", "verb", "/teɪk/", "topic_school_communication"),
    ("need", "verb", "/niːd/", "topic_school_communication"),
    ("want", "verb", "/wɒnt/", "topic_school_communication"),
    ("know", "verb", "/nəʊ/", "topic_school_communication"),
    # topic_market
    ("pineapple", "noun", "/ˈpaɪn.æp.əl/", "topic_market"),
    ("watermelon", "noun", "/ˈwɔː.tə.mel.ən/", "topic_market"),
    ("papaya", "noun", "/pəˈpaɪ.ə/", "topic_market"),
    ("coconut", "noun", "/ˈkəʊ.kə.nʌt/", "topic_market"),
    ("mushroom", "noun", "/ˈmʌʃ.ruːm/", "topic_market"),
    ("spinach", "noun", "/ˈspɪn.ɪtʃ/", "topic_market"),
    ("potato", "noun", "/pəˈteɪ.təʊ/", "topic_market"),
    ("broccoli", "noun", "/ˈbrɒk.ə.li/", "topic_market"),
    ("eggplant", "noun", "/ˈeɡ.plɑːnt/", "topic_market"),
    ("ginger", "noun", "/ˈdʒɪn.dʒər/", "topic_market"),
    ("lime", "noun", "/laɪm/", "topic_market"),
    ("basket", "noun", "/ˈbɑːs.kɪt/", "topic_market"),
    ("bag", "noun", "/bæɡ/", "topic_market"),
    ("box", "noun", "/bɒks/", "topic_market"),
    ("weight", "noun", "/weɪt/", "topic_market"),
    ("money", "noun", "/ˈmʌn.i/", "topic_market"),
    ("coin", "noun", "/kɔɪn/", "topic_market"),
    ("note", "noun", "/nəʊt/", "topic_market"),
    ("hundred", "noun", "/ˈhʌn.drəd/", "topic_market"),
    ("thousand", "noun", "/ˈθaʊ.zənd/", "topic_market"),
    # topic_restaurant
    ("restaurant", "noun", "/ˈres.tər.ɒnt/", "topic_restaurant"),
    ("canteen", "noun", "/kænˈtiːn/", "topic_restaurant"),
    ("kitchen", "noun", "/ˈkɪtʃ.ɪn/", "topic_restaurant"),
    ("cook", "verb", "/kʊk/", "topic_restaurant"),
    ("boil", "verb", "/bɔɪl/", "topic_restaurant"),
    ("fry", "verb", "/fraɪ/", "topic_restaurant"),
    ("steam", "verb", "/stiːm/", "topic_restaurant"),
    ("stir", "verb", "/stɜːr/", "topic_restaurant"),
    ("serve", "verb", "/sɜːv/", "topic_restaurant"),
    ("pour", "verb", "/pɔːr/", "topic_restaurant"),
    ("salt", "noun", "/sɔːlt/", "topic_restaurant"),
    ("sugar", "noun", "/ˈʃʊɡ.ər/", "topic_restaurant"),
    ("oil", "noun", "/ɔɪl/", "topic_restaurant"),
    ("sauce", "noun", "/sɔːs/", "topic_restaurant"),
    ("pepper", "noun", "/ˈpep.ər/", "topic_restaurant"),
    ("chopstick", "noun", "/ˈtʃɒp.stɪk/", "topic_restaurant"),
    ("napkin", "noun", "/ˈnæp.kɪn/", "topic_restaurant"),
    ("tray", "noun", "/treɪ/", "topic_restaurant"),
    # topic_travel
    ("taxi", "noun", "/ˈtæk.si/", "topic_travel"),
    ("ferry", "noun", "/ˈfer.i/", "topic_travel"),
    ("highway", "noun", "/ˈhaɪ.weɪ/", "topic_travel"),
    ("roundabout", "noun", "/ˈraʊnd.ə.baʊt/", "topic_travel"),
    ("traffic", "noun", "/ˈtræf.ɪk/", "topic_travel"),
    ("signal", "noun", "/ˈsɪɡ.nəl/", "topic_travel"),
    ("crossroads", "noun", "/ˈkrɒs.rəʊdz/", "topic_travel"),
    ("corner", "noun", "/ˈkɔː.nər/", "topic_travel"),
    ("distance", "noun", "/ˈdɪs.təns/", "topic_travel"),
    ("minute", "noun", "/ˈmɪn.ɪt/", "topic_travel"),
    ("hour", "noun", "/aʊər/", "topic_travel"),
    ("north", "noun", "/nɔːθ/", "topic_travel"),
    ("south", "noun", "/saʊθ/", "topic_travel"),
    ("east", "noun", "/iːst/", "topic_travel"),
    ("west", "noun", "/west/", "topic_travel"),
    # topic_phone
    ("ring", "verb", "/rɪŋ/", "topic_phone"),
    ("hang", "verb", "/hæŋ/", "topic_phone"),
    ("dial", "verb", "/daɪəl/", "topic_phone"),
    ("connect", "verb", "/kəˈnekt/", "topic_phone"),
    ("cut", "verb", "/kʌt/", "topic_phone"),
    ("charge", "verb", "/tʃɑːdʒ/", "topic_phone"),
    ("save", "verb", "/seɪv/", "topic_phone"),
    ("delete", "verb", "/dɪˈliːt/", "topic_phone"),
    ("speaker", "noun", "/ˈspiː.kər/", "topic_phone"),
    ("volume", "noun", "/ˈvɒl.juːm/", "topic_phone"),
    ("signal", "noun", "/ˈsɪɡ.nəl/", "topic_phone"),
    ("network", "noun", "/ˈnet.wɜːk/", "topic_phone"),
    # topic_health
    ("pain", "noun", "/peɪn/", "topic_health"),
    ("itch", "verb", "/ɪtʃ/", "topic_health"),
    ("bleed", "verb", "/bliːd/", "topic_health"),
    ("breathe", "verb", "/briːð/", "topic_health"),
    ("swallow", "verb", "/ˈswɒl.əʊ/", "topic_health"),
    ("shake", "verb", "/ʃeɪk/", "topic_health"),
    ("faint", "verb", "/feɪnt/", "topic_health"),
    ("dizzy", "adjective", "/ˈdɪz.i/", "topic_health"),
    ("pale", "adjective", "/peɪl/", "topic_health"),
    ("warm", "adjective", "/wɔːm/", "topic_health"),
    ("pharmacy", "noun", "/ˈfɑː.mə.si/", "topic_health"),
    ("injection", "noun", "/ɪnˈdʒek.ʃən/", "topic_health"),
    ("pill", "noun", "/pɪl/", "topic_health"),
    ("cream", "noun", "/kriːm/", "topic_health"),
    ("thermometer", "noun", "/θəˈmɒm.ɪ.tər/", "topic_health"),
    # topic_social
    ("neighbour", "noun", "/ˈneɪ.bər/", "topic_social"),
    ("street", "noun", "/striːt/", "topic_social"),
    ("area", "noun", "/ˈeə.ri.ə/", "topic_social"),
    ("town", "noun", "/taʊn/", "topic_social"),
    ("city", "noun", "/ˈsɪt.i/", "topic_social"),
    ("village", "noun", "/ˈvɪl.ɪdʒ/", "topic_social"),
    ("market", "noun", "/ˈmɑː.kɪt/", "topic_social"),
    ("shop", "noun", "/ʃɒp/", "topic_social"),
    ("bank", "noun", "/bæŋk/", "topic_social"),
    ("post", "noun", "/pəʊst/", "topic_social"),
    ("church", "noun", "/tʃɜːtʃ/", "topic_social"),
    ("temple", "noun", "/ˈtem.pəl/", "topic_social"),
    ("lake", "noun", "/leɪk/", "topic_social"),
    ("river", "noun", "/ˈrɪv.ər/", "topic_social"),
    ("mountain", "noun", "/ˈmaʊn.tɪn/", "topic_social"),
    ("beach", "noun", "/biːtʃ/", "topic_social"),
    ("forest", "noun", "/ˈfɒr.ɪst/", "topic_social"),
    ("garden", "noun", "/ˈɡɑː.dən/", "topic_social"),
    ("sky", "noun", "/skaɪ/", "topic_social"),
    ("cloud", "noun", "/klaʊd/", "topic_social"),
    ("snow", "noun", "/snəʊ/", "topic_social"),
    ("storm", "noun", "/stɔːm/", "topic_social"),
    ("spring", "noun", "/sprɪŋ/", "topic_social"),
    ("summer", "noun", "/ˈsʌm.ər/", "topic_social"),
    ("autumn", "noun", "/ˈɔː.təm/", "topic_social"),
    ("winter", "noun", "/ˈwɪn.tər/", "topic_social"),
],

"flyers": [
    # topic_before_class
    ("professional", "adjective", "/prəˈfeʃ.ən.əl/", "topic_before_class"),
    ("efficient", "adjective", "/ɪˈfɪʃ.ənt/", "topic_before_class"),
    ("thorough", "adjective", "/ˈθʌr.ə/", "topic_before_class"),
    ("systematic", "adjective", "/ˌsɪs.təˈmæt.ɪk/", "topic_before_class"),
    ("organised", "adjective", "/ˈɔː.ɡən.aɪzd/", "topic_before_class"),
    ("logistic", "noun", "/ləˈdʒɪs.tɪk/", "topic_before_class"),
    ("outline", "noun", "/ˈaʊt.laɪn/", "topic_before_class"),
    ("overview", "noun", "/ˈəʊ.və.vjuː/", "topic_before_class"),
    ("objective", "noun", "/əbˈdʒek.tɪv/", "topic_before_class"),
    ("target", "noun", "/ˈtɑː.ɡɪt/", "topic_before_class"),
    ("goal", "noun", "/ɡəʊl/", "topic_before_class"),
    ("aim", "noun", "/eɪm/", "topic_before_class"),
    ("framework", "noun", "/ˈfreɪm.wɜːk/", "topic_before_class"),
    ("template", "noun", "/ˈtem.plɪt/", "topic_before_class"),
    ("format", "noun", "/ˈfɔː.mæt/", "topic_before_class"),
    ("draft", "noun", "/drɑːft/", "topic_before_class"),
    ("version", "noun", "/ˈvɜː.ʒən/", "topic_before_class"),
    ("copy", "noun", "/ˈkɒp.i/", "topic_before_class"),
    ("print", "noun", "/prɪnt/", "topic_before_class"),
    ("file", "noun", "/faɪl/", "topic_before_class"),
    # topic_in_class
    ("debate", "noun", "/dɪˈbeɪt/", "topic_in_class"),
    ("argument", "noun", "/ˈɑː.ɡjʊ.mənt/", "topic_in_class"),
    ("evidence", "noun", "/ˈev.ɪ.dəns/", "topic_in_class"),
    ("source", "noun", "/sɔːs/", "topic_in_class"),
    ("reference", "noun", "/ˈref.ər.əns/", "topic_in_class"),
    ("conclusion", "noun", "/kənˈkluː.ʒən/", "topic_in_class"),
    ("introduction", "noun", "/ˌɪn.trəˈdʌk.ʃən/", "topic_in_class"),
    ("body", "noun", "/ˈbɒd.i/", "topic_in_class"),
    ("paragraph", "noun", "/ˈpær.ə.ɡrɑːf/", "topic_in_class"),
    ("sentence", "noun", "/ˈsen.təns/", "topic_in_class"),
    ("phrase", "noun", "/freɪz/", "topic_in_class"),
    ("clause", "noun", "/klɔːz/", "topic_in_class"),
    ("tense", "noun", "/tens/", "topic_in_class"),
    ("subject", "noun", "/ˈsʌb.dʒɪkt/", "topic_in_class"),
    ("object", "noun", "/ˈɒb.dʒɪkt/", "topic_in_class"),
    ("pronoun", "noun", "/ˈprəʊ.naʊn/", "topic_in_class"),
    ("adjective", "noun", "/ˈædʒ.ɪk.tɪv/", "topic_in_class"),
    ("adverb", "noun", "/ˈæd.vɜːb/", "topic_in_class"),
    ("preposition", "noun", "/ˌprep.əˈzɪʃ.ən/", "topic_in_class"),
    ("conjunction", "noun", "/kənˈdʒʌŋk.ʃən/", "topic_in_class"),
    # topic_giving_instructions
    ("emphasis", "noun", "/ˈem.fə.sɪs/", "topic_giving_instructions"),
    ("highlight", "verb", "/ˈhaɪ.laɪt/", "topic_giving_instructions"),
    ("clarify", "verb", "/ˈklær.ɪ.faɪ/", "topic_giving_instructions"),
    ("simplify", "verb", "/ˈsɪm.plɪ.faɪ/", "topic_giving_instructions"),
    ("specify", "verb", "/ˈspes.ɪ.faɪ/", "topic_giving_instructions"),
    ("indicate", "verb", "/ˈɪn.dɪ.keɪt/", "topic_giving_instructions"),
    ("require", "verb", "/rɪˈkwaɪər/", "topic_giving_instructions"),
    ("restrict", "verb", "/rɪˈstrɪkt/", "topic_giving_instructions"),
    ("allow", "verb", "/əˈlaʊ/", "topic_giving_instructions"),
    ("permit", "verb", "/pəˈmɪt/", "topic_giving_instructions"),
    ("forbid", "verb", "/fəˈbɪd/", "topic_giving_instructions"),
    ("warn", "verb", "/wɔːn/", "topic_giving_instructions"),
    ("remind", "verb", "/rɪˈmaɪnd/", "topic_giving_instructions"),
    ("instruct", "verb", "/ɪnˈstrʌkt/", "topic_giving_instructions"),
    ("direct", "verb", "/daɪˈrekt/", "topic_giving_instructions"),
    # topic_checking_understanding
    ("clarification", "noun", "/ˌklær.ɪ.fɪˈkeɪ.ʃən/", "topic_checking_understanding"),
    ("verification", "noun", "/ˌver.ɪ.fɪˈkeɪ.ʃən/", "topic_checking_understanding"),
    ("confirmation", "noun", "/ˌkɒn.fəˈmeɪ.ʃən/", "topic_checking_understanding"),
    ("probe", "verb", "/prəʊb/", "topic_checking_understanding"),
    ("investigate", "verb", "/ɪnˈves.tɪ.ɡeɪt/", "topic_checking_understanding"),
    ("explore", "verb", "/ɪkˈsplɔːr/", "topic_checking_understanding"),
    ("discover", "verb", "/dɪˈskʌv.ər/", "topic_checking_understanding"),
    ("reveal", "verb", "/rɪˈviːl/", "topic_checking_understanding"),
    ("demonstrate", "verb", "/ˈdem.ən.streɪt/", "topic_checking_understanding"),
    ("show", "verb", "/ʃəʊ/", "topic_checking_understanding"),
    ("prove", "verb", "/pruːv/", "topic_checking_understanding"),
    ("test", "verb", "/test/", "topic_checking_understanding"),
    ("measure", "verb", "/ˈmeʒ.ər/", "topic_checking_understanding"),
    ("record", "verb", "/rɪˈkɔːd/", "topic_checking_understanding"),
    ("document", "verb", "/ˈdɒk.jʊ.ment/", "topic_checking_understanding"),
    # topic_praise_correction
    ("grade", "noun", "/ɡreɪd/", "topic_praise_correction"),
    ("result", "noun", "/rɪˈzʌlt/", "topic_praise_correction"),
    ("performance", "noun", "/pəˈfɔː.məns/", "topic_praise_correction"),
    ("standard", "noun", "/ˈstæn.dəd/", "topic_praise_correction"),
    ("quality", "noun", "/ˈkwɒl.ɪ.ti/", "topic_praise_correction"),
    ("accuracy", "noun", "/ˈæk.jʊ.rə.si/", "topic_praise_correction"),
    ("fluency", "noun", "/ˈfluː.ən.si/", "topic_praise_correction"),
    ("improve", "verb", "/ɪmˈpruːv/", "topic_praise_correction"),
    ("develop", "verb", "/dɪˈvel.əp/", "topic_praise_correction"),
    ("strengthen", "verb", "/ˈstreŋ.θən/", "topic_praise_correction"),
    ("build", "verb", "/bɪld/", "topic_praise_correction"),
    ("boost", "verb", "/buːst/", "topic_praise_correction"),
    ("encourage", "verb", "/ɪnˈkʌr.ɪdʒ/", "topic_praise_correction"),
    ("motivate", "verb", "/ˈməʊ.tɪ.veɪt/", "topic_praise_correction"),
    ("inspire", "verb", "/ɪnˈspaɪər/", "topic_praise_correction"),
    # topic_school_communication
    ("collaborate", "verb", "/kəˈlæb.ər.eɪt/", "topic_school_communication"),
    ("consult", "verb", "/kənˈsʌlt/", "topic_school_communication"),
    ("advise", "verb", "/ədˈvaɪz/", "topic_school_communication"),
    ("refer", "verb", "/rɪˈfɜːr/", "topic_school_communication"),
    ("recommend", "verb", "/ˌrek.əˈmend/", "topic_school_communication"),
    ("propose", "verb", "/prəˈpəʊz/", "topic_school_communication"),
    ("arrange", "verb", "/əˈreɪndʒ/", "topic_school_communication"),
    ("organise", "verb", "/ˈɔː.ɡən.aɪz/", "topic_school_communication"),
    ("manage", "verb", "/ˈmæn.ɪdʒ/", "topic_school_communication"),
    ("handle", "verb", "/ˈhæn.dəl/", "topic_school_communication"),
    ("deal", "verb", "/diːl/", "topic_school_communication"),
    ("address", "verb", "/əˈdres/", "topic_school_communication"),
    ("respond", "verb", "/rɪˈspɒnd/", "topic_school_communication"),
    ("follow", "verb", "/ˈfɒl.əʊ/", "topic_school_communication"),
    # topic_market
    ("seasonal", "adjective", "/ˈsiː.zən.əl/", "topic_market"),
    ("local", "adjective", "/ˈləʊ.kəl/", "topic_market"),
    ("imported", "adjective", "/ɪmˈpɔː.tɪd/", "topic_market"),
    ("ripe", "adjective", "/raɪp/", "topic_market"),
    ("rotten", "adjective", "/ˈrɒt.ən/", "topic_market"),
    ("packed", "adjective", "/pækt/", "topic_market"),
    ("wrapped", "adjective", "/ræpt/", "topic_market"),
    ("frozen", "adjective", "/ˈfrəʊ.zən/", "topic_market"),
    ("dried", "adjective", "/draɪd/", "topic_market"),
    ("pickled", "adjective", "/ˈpɪk.əld/", "topic_market"),
    ("quantity", "noun", "/ˈkwɒn.tɪ.ti/", "topic_market"),
    ("variety", "noun", "/vəˈraɪ.ɪ.ti/", "topic_market"),
    ("quality", "noun", "/ˈkwɒl.ɪ.ti/", "topic_market"),
    ("supply", "noun", "/səˈplaɪ/", "topic_market"),
    ("demand", "noun", "/dɪˈmɑːnd/", "topic_market"),
    # topic_restaurant
    ("cuisine", "noun", "/kwɪˈziːn/", "topic_restaurant"),
    ("specialty", "noun", "/ˈspeʃ.əl.ti/", "topic_restaurant"),
    ("signature", "adjective", "/ˈsɪɡ.nɪ.tʃər/", "topic_restaurant"),
    ("authentic", "adjective", "/ɔːˈθen.tɪk/", "topic_restaurant"),
    ("traditional", "adjective", "/trəˈdɪʃ.ən.əl/", "topic_restaurant"),
    ("homemade", "adjective", "/ˈhəʊm.meɪd/", "topic_restaurant"),
    ("grilled", "adjective", "/ɡrɪld/", "topic_restaurant"),
    ("baked", "adjective", "/beɪkt/", "topic_restaurant"),
    ("roasted", "adjective", "/ˈrəʊ.stɪd/", "topic_restaurant"),
    ("marinated", "adjective", "/ˈmær.ɪ.neɪ.tɪd/", "topic_restaurant"),
    ("nutritious", "adjective", "/njuːˈtrɪʃ.əs/", "topic_restaurant"),
    ("balanced", "adjective", "/ˈbæl.ənst/", "topic_restaurant"),
    ("calorie", "noun", "/ˈkæl.ər.i/", "topic_restaurant"),
    ("protein", "noun", "/ˈprəʊ.tiːn/", "topic_restaurant"),
    ("fibre", "noun", "/ˈfaɪ.bər/", "topic_restaurant"),
    # topic_travel
    ("location", "noun", "/ləʊˈkeɪ.ʃən/", "topic_travel"),
    ("route", "noun", "/ruːt/", "topic_travel"),
    ("map", "noun", "/mæp/", "topic_travel"),
    ("guide", "noun", "/ɡaɪd/", "topic_travel"),
    ("tour", "noun", "/tʊər/", "topic_travel"),
    ("tourist", "noun", "/ˈtʊər.ɪst/", "topic_travel"),
    ("attraction", "noun", "/əˈtræk.ʃən/", "topic_travel"),
    ("sight", "noun", "/saɪt/", "topic_travel"),
    ("landmark", "noun", "/ˈlænd.mɑːk/", "topic_travel"),
    ("scenery", "noun", "/ˈsiː.nər.i/", "topic_travel"),
    ("landscape", "noun", "/ˈlænd.skeɪp/", "topic_travel"),
    ("climate", "noun", "/ˈklaɪ.mɪt/", "topic_travel"),
    ("season", "noun", "/ˈsiː.zən/", "topic_travel"),
    ("temperature", "noun", "/ˈtem.prɪ.tʃər/", "topic_travel"),
    ("forecast", "noun", "/ˈfɔː.kɑːst/", "topic_travel"),
    # topic_phone
    ("connection", "noun", "/kəˈnek.ʃən/", "topic_phone"),
    ("reception", "noun", "/rɪˈsep.ʃən/", "topic_phone"),
    ("interference", "noun", "/ˌɪn.təˈfɪər.əns/", "topic_phone"),
    ("notification", "noun", "/ˌnəʊ.tɪ.fɪˈkeɪ.ʃən/", "topic_phone"),
    ("reminder", "noun", "/rɪˈmaɪn.dər/", "topic_phone"),
    ("alert", "noun", "/əˈlɜːt/", "topic_phone"),
    ("application", "noun", "/ˌæp.lɪˈkeɪ.ʃən/", "topic_phone"),
    ("device", "noun", "/dɪˈvaɪs/", "topic_phone"),
    ("password", "noun", "/ˈpɑːs.wɜːd/", "topic_phone"),
    ("internet", "noun", "/ˈɪn.tə.net/", "topic_phone"),
    # topic_health
    ("posture", "noun", "/ˈpɒs.tʃər/", "topic_health"),
    ("nutrition", "noun", "/njuːˈtrɪʃ.ən/", "topic_health"),
    ("exercise", "noun", "/ˈek.sə.saɪz/", "topic_health"),
    ("stress", "noun", "/stres/", "topic_health"),
    ("anxiety", "noun", "/æŋˈzaɪ.ɪ.ti/", "topic_health"),
    ("relaxation", "noun", "/ˌriː.læk.ˈseɪ.ʃən/", "topic_health"),
    ("hygiene", "noun", "/ˈhaɪ.dʒiːn/", "topic_health"),
    ("sanitation", "noun", "/ˌsæn.ɪˈteɪ.ʃən/", "topic_health"),
    ("immune", "adjective", "/ɪˈmjuːn/", "topic_health"),
    ("vitamin", "noun", "/ˈvɪt.ə.mɪn/", "topic_health"),
    ("mineral", "noun", "/ˈmɪn.ər.əl/", "topic_health"),
    ("supplement", "noun", "/ˈsʌp.lɪ.mənt/", "topic_health"),
    ("dose", "noun", "/dəʊs/", "topic_health"),
    # topic_social
    ("volunteering", "noun", "/ˌvɒl.ənˈtɪər.ɪŋ/", "topic_social"),
    ("charity", "noun", "/ˈtʃær.ɪ.ti/", "topic_social"),
    ("campaign", "noun", "/kæmˈpeɪn/", "topic_social"),
    ("project", "noun", "/ˈprɒdʒ.ekt/", "topic_social"),
    ("fundraiser", "noun", "/ˈfʌnd.reɪ.zər/", "topic_social"),
    ("event", "noun", "/ɪˈvent/", "topic_social"),
    ("celebration", "noun", "/ˌsel.ɪˈbreɪ.ʃən/", "topic_social"),
    ("festival", "noun", "/ˈfes.tɪ.vəl/", "topic_social"),
    ("ceremony", "noun", "/ˈser.ɪ.mə.ni/", "topic_social"),
    ("occasion", "noun", "/əˈkeɪ.ʒən/", "topic_social"),
    ("gathering", "noun", "/ˈɡæð.ər.ɪŋ/", "topic_social"),
    ("reunion", "noun", "/riːˈjuː.ni.ən/", "topic_social"),
    ("anniversary", "noun", "/ˌæn.ɪˈvɜː.sər.i/", "topic_social"),
    ("congratulation", "noun", "/kənˌɡræt.jʊˈleɪ.ʃən/", "topic_social"),
    ("appreciate", "verb", "/əˈpriː.ʃi.eɪt/", "topic_social"),
    ("respect", "verb", "/rɪˈspekt/", "topic_social"),
    ("trust", "verb", "/trʌst/", "topic_social"),
    ("support", "verb", "/səˈpɔːt/", "topic_social"),
    ("encourage", "verb", "/ɪnˈkʌr.ɪdʒ/", "topic_social"),
],

"ket": [
    # topic_before_class
    ("pedagogical", "adjective", "/ˌped.əˈɡɒdʒ.ɪ.kəl/", "topic_before_class"),
    ("differentiated", "adjective", "/ˌdɪf.ər.enˈʃi.eɪ.tɪd/", "topic_before_class"),
    ("integrated", "adjective", "/ˈɪn.tɪ.ɡreɪ.tɪd/", "topic_before_class"),
    ("structured", "adjective", "/ˈstrʌk.tʃəd/", "topic_before_class"),
    ("coherent", "adjective", "/kəʊˈhɪər.ənt/", "topic_before_class"),
    ("sequential", "adjective", "/sɪˈkwen.ʃəl/", "topic_before_class"),
    ("revision", "noun", "/rɪˈvɪʒ.ən/", "topic_before_class"),
    ("rationale", "noun", "/ˌræʃ.əˈnɑːl/", "topic_before_class"),
    ("specification", "noun", "/ˌspes.ɪ.fɪˈkeɪ.ʃən/", "topic_before_class"),
    ("benchmark", "noun", "/ˈbentʃ.mɑːk/", "topic_before_class"),
    ("rubric", "noun", "/ˈruː.brɪk/", "topic_before_class"),
    ("indicator", "noun", "/ˈɪn.dɪ.keɪ.tər/", "topic_before_class"),
    ("milestone", "noun", "/ˈmaɪl.stəʊn/", "topic_before_class"),
    ("portfolio", "noun", "/pɔːtˈfəʊ.li.əʊ/", "topic_before_class"),
    # topic_in_class
    ("constructivist", "adjective", "/kənˈstrʌk.tɪ.vɪst/", "topic_in_class"),
    ("collaborative", "adjective", "/kəˈlæb.ər.ə.tɪv/", "topic_in_class"),
    ("communicative", "adjective", "/kəˈmjuː.nɪ.kə.tɪv/", "topic_in_class"),
    ("student-centred", "adjective", "/ˈstjuː.dənt ˈsen.təd/", "topic_in_class"),
    ("task-based", "adjective", "/ˈtɑːsk beɪst/", "topic_in_class"),
    ("inquiry", "noun", "/ɪnˈkwaɪər.i/", "topic_in_class"),
    ("scaffold", "verb", "/ˈskæf.əld/", "topic_in_class"),
    ("differentiate", "verb", "/ˌdɪf.ərˈen.ʃi.eɪt/", "topic_in_class"),
    ("facilitate", "verb", "/fəˈsɪl.ɪ.teɪt/", "topic_in_class"),
    ("integrate", "verb", "/ˈɪn.tɪ.ɡreɪt/", "topic_in_class"),
    ("incorporate", "verb", "/ɪnˈkɔː.pər.eɪt/", "topic_in_class"),
    ("sequence", "verb", "/ˈsiː.kwəns/", "topic_in_class"),
    ("model", "verb", "/ˈmɒd.əl/", "topic_in_class"),
    ("illustrate", "verb", "/ˈɪl.ə.streɪt/", "topic_in_class"),
    ("reinforce", "verb", "/ˌriː.ɪnˈfɔːs/", "topic_in_class"),
    # topic_giving_instructions
    ("benchmark", "verb", "/ˈbentʃ.mɑːk/", "topic_giving_instructions"),
    ("standardise", "verb", "/ˈstæn.də.daɪz/", "topic_giving_instructions"),
    ("align", "verb", "/əˈlaɪn/", "topic_giving_instructions"),
    ("justify", "verb", "/ˈdʒʌs.tɪ.faɪ/", "topic_giving_instructions"),
    ("articulate", "verb", "/ɑːˈtɪk.jʊ.leɪt/", "topic_giving_instructions"),
    ("negotiate", "verb", "/nɪˈɡəʊ.ʃi.eɪt/", "topic_giving_instructions"),
    ("arbitrate", "verb", "/ˈɑː.bɪ.treɪt/", "topic_giving_instructions"),
    ("resolve", "verb", "/rɪˈzɒlv/", "topic_giving_instructions"),
    ("mediate", "verb", "/ˈmiː.di.eɪt/", "topic_giving_instructions"),
    ("oversee", "verb", "/ˌəʊ.vəˈsiː/", "topic_giving_instructions"),
    # topic_checking_understanding
    ("benchmark", "noun", "/ˈbentʃ.mɑːk/", "topic_checking_understanding"),
    ("criterion", "noun", "/kraɪˈtɪər.i.ən/", "topic_checking_understanding"),
    ("threshold", "noun", "/ˈθreʃ.həʊld/", "topic_checking_understanding"),
    ("standard", "noun", "/ˈstæn.dəd/", "topic_checking_understanding"),
    ("validity", "noun", "/vəˈlɪd.ɪ.ti/", "topic_checking_understanding"),
    ("reliability", "noun", "/rɪˌlaɪ.əˈbɪl.ɪ.ti/", "topic_checking_understanding"),
    ("authenticity", "noun", "/ˌɔː.θenˈtɪs.ɪ.ti/", "topic_checking_understanding"),
    ("triangulation", "noun", "/traɪˌæŋ.ɡjʊˈleɪ.ʃən/", "topic_checking_understanding"),
    ("formative", "adjective", "/ˈfɔː.mə.tɪv/", "topic_checking_understanding"),
    ("summative", "adjective", "/ˈsʌm.ə.tɪv/", "topic_checking_understanding"),
    # topic_praise_correction
    ("commend", "verb", "/kəˈmend/", "topic_praise_correction"),
    ("applaud", "verb", "/əˈplɔːd/", "topic_praise_correction"),
    ("celebrate", "verb", "/ˈsel.ɪ.breɪt/", "topic_praise_correction"),
    ("highlight", "verb", "/ˈhaɪ.laɪt/", "topic_praise_correction"),
    ("pinpoint", "verb", "/ˈpɪn.pɔɪnt/", "topic_praise_correction"),
    ("target", "verb", "/ˈtɑː.ɡɪt/", "topic_praise_correction"),
    ("address", "verb", "/əˈdres/", "topic_praise_correction"),
    ("overcome", "verb", "/ˌəʊ.vəˈkʌm/", "topic_praise_correction"),
    ("rectify", "verb", "/ˈrek.tɪ.faɪ/", "topic_praise_correction"),
    ("enhance", "verb", "/ɪnˈhɑːns/", "topic_praise_correction"),
    # topic_school_communication
    ("stakeholder", "noun", "/ˈsteɪk.həʊl.dər/", "topic_school_communication"),
    ("framework", "noun", "/ˈfreɪm.wɜːk/", "topic_school_communication"),
    ("strategy", "noun", "/ˈstræt.ɪ.dʒi/", "topic_school_communication"),
    ("initiative", "noun", "/ɪˈnɪʃ.ɪ.tɪv/", "topic_school_communication"),
    ("intervention", "noun", "/ˌɪn.təˈven.ʃən/", "topic_school_communication"),
    ("outreach", "noun", "/ˈaʊt.riːtʃ/", "topic_school_communication"),
    ("liaison", "noun", "/liˈeɪ.zɒn/", "topic_school_communication"),
    ("coordinator", "noun", "/kəʊˈɔː.dɪ.neɪ.tər/", "topic_school_communication"),
    ("moderator", "noun", "/ˈmɒd.ər.eɪ.tər/", "topic_school_communication"),
    ("facilitator", "noun", "/fəˈsɪl.ɪ.teɪ.tər/", "topic_school_communication"),
    # topic_market
    ("wholesaler", "noun", "/ˈhəʊl.seɪ.lər/", "topic_market"),
    ("retailer", "noun", "/ˈriː.teɪ.lər/", "topic_market"),
    ("distributor", "noun", "/dɪˈstrɪb.jʊ.tər/", "topic_market"),
    ("consumer", "noun", "/kənˈsjuː.mər/", "topic_market"),
    ("producer", "noun", "/prəˈdjuː.sər/", "topic_market"),
    ("competitor", "noun", "/kəmˈpet.ɪ.tər/", "topic_market"),
    ("supplier", "noun", "/səˈplaɪ.ər/", "topic_market"),
    ("profit", "noun", "/ˈprɒf.ɪt/", "topic_market"),
    ("loss", "noun", "/lɒs/", "topic_market"),
    ("revenue", "noun", "/ˈrev.ɪ.njuː/", "topic_market"),
    ("margin", "noun", "/ˈmɑː.dʒɪn/", "topic_market"),
    ("overhead", "noun", "/ˈəʊ.vər.hed/", "topic_market"),
    # topic_restaurant
    ("sommelier", "noun", "/ˈsɒm.əl.jeɪ/", "topic_restaurant"),
    ("maitre", "noun", "/ˈmeɪ.trə/", "topic_restaurant"),
    ("establishment", "noun", "/ɪˈstæb.lɪʃ.mənt/", "topic_restaurant"),
    ("ambiance", "noun", "/ˈæm.bi.ɑːns/", "topic_restaurant"),
    ("decor", "noun", "/ˈdeɪ.kɔːr/", "topic_restaurant"),
    ("presentation", "noun", "/ˌprez.ənˈteɪ.ʃən/", "topic_restaurant"),
    ("garnish", "noun", "/ˈɡɑː.nɪʃ/", "topic_restaurant"),
    ("pairing", "noun", "/ˈpeər.ɪŋ/", "topic_restaurant"),
    ("complimentary", "adjective", "/ˌkɒm.plɪˈmen.tri/", "topic_restaurant"),
    ("exclusive", "adjective", "/ɪkˈskluː.sɪv/", "topic_restaurant"),
    # topic_travel
    ("expedition", "noun", "/ˌek.spɪˈdɪʃ.ən/", "topic_travel"),
    ("excursion", "noun", "/ɪkˈskɜː.ʒən/", "topic_travel"),
    ("backpacker", "noun", "/ˈbæk.pæk.ər/", "topic_travel"),
    ("hostel", "noun", "/ˈhɒs.təl/", "topic_travel"),
    ("resort", "noun", "/rɪˈzɔːt/", "topic_travel"),
    ("embarkation", "noun", "/ˌem.bɑːˈkeɪ.ʃən/", "topic_travel"),
    ("disembark", "verb", "/ˌdɪs.ɪmˈbɑːk/", "topic_travel"),
    ("navigate", "verb", "/ˈnæv.ɪ.ɡeɪt/", "topic_travel"),
    ("orient", "verb", "/ˈɔː.ri.ent/", "topic_travel"),
    ("detour", "noun", "/ˈdiː.tʊər/", "topic_travel"),
    # topic_phone
    ("telecommunications", "noun", "/ˌtel.ɪ.kəˌmjuː.nɪˈkeɪ.ʃənz/", "topic_phone"),
    ("broadband", "noun", "/ˈbrɔːd.bænd/", "topic_phone"),
    ("bandwidth", "noun", "/ˈbænd.wɪdθ/", "topic_phone"),
    ("latency", "noun", "/ˈleɪ.tən.si/", "topic_phone"),
    ("encryption", "noun", "/ɪnˈkrɪp.ʃən/", "topic_phone"),
    ("interface", "noun", "/ˈɪn.tə.feɪs/", "topic_phone"),
    ("protocol", "noun", "/ˈprəʊ.tə.kɒl/", "topic_phone"),
    ("synchronise", "verb", "/ˈsɪŋ.krə.naɪz/", "topic_phone"),
    ("authenticate", "verb", "/ɔːˈθen.tɪ.keɪt/", "topic_phone"),
    # topic_health
    ("cardiovascular", "adjective", "/ˌkɑː.di.əʊˈvæs.kjʊ.lər/", "topic_health"),
    ("respiratory", "adjective", "/rɪˈspɪr.ə.tər.i/", "topic_health"),
    ("neurological", "adjective", "/ˌnjʊər.əˈlɒdʒ.ɪ.kəl/", "topic_health"),
    ("psychological", "adjective", "/ˌsaɪ.kəˈlɒdʒ.ɪ.kəl/", "topic_health"),
    ("physiotherapy", "noun", "/ˌfɪz.i.əʊˈθer.ə.pi/", "topic_health"),
    ("immunisation", "noun", "/ˌɪm.jʊ.naɪˈzeɪ.ʃən/", "topic_health"),
    ("consultation", "noun", "/ˌkɒn.sʌlˈteɪ.ʃən/", "topic_health"),
    ("referral", "noun", "/rɪˈfɜː.rəl/", "topic_health"),
    ("prognosis", "noun", "/prɒɡˈnəʊ.sɪs/", "topic_health"),
    ("pathology", "noun", "/pəˈθɒl.ə.dʒi/", "topic_health"),
    # topic_social
    ("etiquette", "noun", "/ˈet.ɪ.kɪt/", "topic_social"),
    ("diplomacy", "noun", "/dɪˈpləʊ.mə.si/", "topic_social"),
    ("hierarchy", "noun", "/ˈhaɪ.ə.rɑː.ki/", "topic_social"),
    ("solidarity", "noun", "/ˌsɒl.ɪˈdær.ɪ.ti/", "topic_social"),
    ("diversity", "noun", "/daɪˈvɜː.sɪ.ti/", "topic_social"),
    ("inclusion", "noun", "/ɪnˈkluː.ʒən/", "topic_social"),
    ("tolerance", "noun", "/ˈtɒl.ər.əns/", "topic_social"),
    ("empathy", "noun", "/ˈem.pə.θi/", "topic_social"),
    ("compassion", "noun", "/kəmˈpæʃ.ən/", "topic_social"),
    ("integrity", "noun", "/ɪnˈteɡ.rɪ.ti/", "topic_social"),
],

"pet": [
    # topic_before_class
    ("epistemological", "adjective", "/ɪˌpɪs.tɪ.məˈlɒdʒ.ɪ.kəl/", "topic_before_class"),
    ("heuristic", "adjective", "/hjʊˈrɪs.tɪk/", "topic_before_class"),
    ("paradigm", "noun", "/ˈpær.ə.daɪm/", "topic_before_class"),
    ("praxis", "noun", "/ˈpræk.sɪs/", "topic_before_class"),
    ("disposition", "noun", "/ˌdɪs.pəˈzɪʃ.ən/", "topic_before_class"),
    ("prerequisite", "noun", "/ˌpriːˈrek.wɪ.zɪt/", "topic_before_class"),
    ("contingency", "noun", "/kənˈtɪn.dʒən.si/", "topic_before_class"),
    ("rationale", "noun", "/ˌræʃ.əˈnɑːl/", "topic_before_class"),
    ("taxonomy", "noun", "/tækˈsɒn.ə.mi/", "topic_before_class"),
    ("meta-cognition", "noun", "/ˌmet.ə.kɒɡˈnɪʃ.ən/", "topic_before_class"),
    # topic_in_class
    ("discourse", "noun", "/ˈdɪs.kɔːs/", "topic_in_class"),
    ("rhetoric", "noun", "/ˈret.ər.ɪk/", "topic_in_class"),
    ("dialectic", "noun", "/ˌdaɪ.əˈlek.tɪk/", "topic_in_class"),
    ("synthesis", "noun", "/ˈsɪn.θə.sɪs/", "topic_in_class"),
    ("abstraction", "noun", "/æbˈstræk.ʃən/", "topic_in_class"),
    ("conceptualise", "verb", "/kənˈsep.tʃʊ.ə.laɪz/", "topic_in_class"),
    ("contextualise", "verb", "/kənˈteks.tʃʊ.ə.laɪz/", "topic_in_class"),
    ("operationalise", "verb", "/ˌɒp.ər.ˈeɪʃ.ən.ə.laɪz/", "topic_in_class"),
    ("problematise", "verb", "/ˈprɒb.ləm.ə.taɪz/", "topic_in_class"),
    ("interrogate", "verb", "/ɪnˈter.ə.ɡeɪt/", "topic_in_class"),
    # topic_giving_instructions
    ("circumscribe", "verb", "/ˈsɜː.kəm.skraɪb/", "topic_giving_instructions"),
    ("delineate", "verb", "/dɪˈlɪn.i.eɪt/", "topic_giving_instructions"),
    ("stipulate", "verb", "/ˈstɪp.jʊ.leɪt/", "topic_giving_instructions"),
    ("mandate", "verb", "/ˈmæn.deɪt/", "topic_giving_instructions"),
    ("prescribe", "verb", "/prɪˈskraɪb/", "topic_giving_instructions"),
    ("proscribe", "verb", "/prəʊˈskraɪb/", "topic_giving_instructions"),
    ("sanction", "verb", "/ˈsæŋk.ʃən/", "topic_giving_instructions"),
    ("enforce", "verb", "/ɪnˈfɔːs/", "topic_giving_instructions"),
    ("regulate", "verb", "/ˈreɡ.jʊ.leɪt/", "topic_giving_instructions"),
    ("govern", "verb", "/ˈɡʌv.ən/", "topic_giving_instructions"),
    # topic_checking_understanding
    ("epistemology", "noun", "/ɪˌpɪs.tɪˈmɒl.ə.dʒi/", "topic_checking_understanding"),
    ("ontology", "noun", "/ɒnˈtɒl.ə.dʒi/", "topic_checking_understanding"),
    ("phenomenology", "noun", "/fɪˌnɒm.ɪˈnɒl.ə.dʒi/", "topic_checking_understanding"),
    ("hermeneutics", "noun", "/ˌhɜː.mɪˈnjuː.tɪks/", "topic_checking_understanding"),
    ("deconstruct", "verb", "/ˌdiː.kənˈstrʌkt/", "topic_checking_understanding"),
    ("problematise", "verb", "/ˈprɒb.ləm.ə.taɪz/", "topic_checking_understanding"),
    ("recontextualise", "verb", "/ˌriː.kənˈteks.tʃʊ.ə.laɪz/", "topic_checking_understanding"),
    ("meta-analyse", "verb", "/ˌmet.əˈæn.ə.laɪz/", "topic_checking_understanding"),
    ("synthesise", "verb", "/ˈsɪn.θə.saɪz/", "topic_checking_understanding"),
    ("extrapolate", "verb", "/ɪkˈstræp.ə.leɪt/", "topic_checking_understanding"),
    # topic_praise_correction
    ("exemplar", "noun", "/ɪɡˈzem.plər/", "topic_praise_correction"),
    ("benchmark", "noun", "/ˈbentʃ.mɑːk/", "topic_praise_correction"),
    ("commendation", "noun", "/ˌkɒm.enˈdeɪ.ʃən/", "topic_praise_correction"),
    ("distinction", "noun", "/dɪˈstɪŋk.ʃən/", "topic_praise_correction"),
    ("meritorious", "adjective", "/ˌmer.ɪˈtɔː.ri.əs/", "topic_praise_correction"),
    ("praiseworthy", "adjective", "/ˈpreɪz.wɜː.ði/", "topic_praise_correction"),
    ("noteworthy", "adjective", "/ˈnəʊt.wɜː.ði/", "topic_praise_correction"),
    ("outstanding", "adjective", "/ˌaʊtˈstæn.dɪŋ/", "topic_praise_correction"),
    ("commendable", "adjective", "/kəˈmen.də.bəl/", "topic_praise_correction"),
    ("impeccable", "adjective", "/ɪmˈpek.ə.bəl/", "topic_praise_correction"),
    # topic_school_communication
    ("correspondence", "noun", "/ˌkɒr.ɪˈspɒn.dəns/", "topic_school_communication"),
    ("communiqué", "noun", "/kəˈmjuː.nɪ.keɪ/", "topic_school_communication"),
    ("memorandum", "noun", "/ˌmem.əˈræn.dəm/", "topic_school_communication"),
    ("manifesto", "noun", "/ˌmæn.ɪˈfes.təʊ/", "topic_school_communication"),
    ("ombudsman", "noun", "/ˈɒm.bʊdz.mən/", "topic_school_communication"),
    ("arbitration", "noun", "/ˌɑː.bɪˈtreɪ.ʃən/", "topic_school_communication"),
    ("adjudication", "noun", "/ədˌdʒuː.dɪˈkeɪ.ʃən/", "topic_school_communication"),
    ("deliberation", "noun", "/dɪˌlɪb.ərˈeɪ.ʃən/", "topic_school_communication"),
    ("ratification", "noun", "/ˌræt.ɪ.fɪˈkeɪ.ʃən/", "topic_school_communication"),
    ("promulgation", "noun", "/ˌprɒm.ʌlˈɡeɪ.ʃən/", "topic_school_communication"),
    # topic_market
    ("macroeconomics", "noun", "/ˌmæk.rəʊˌiː.kəˈnɒm.ɪks/", "topic_market"),
    ("microeconomics", "noun", "/ˌmaɪ.krəʊˌiː.kəˈnɒm.ɪks/", "topic_market"),
    ("equilibrium", "noun", "/ˌiː.kwɪˈlɪb.ri.əm/", "topic_market"),
    ("oligopoly", "noun", "/ˌɒl.ɪˈɡɒp.ə.li/", "topic_market"),
    ("monopoly", "noun", "/məˈnɒp.ə.li/", "topic_market"),
    ("elasticity", "noun", "/ˌɪ.læsˈtɪs.ɪ.ti/", "topic_market"),
    ("depreciation", "noun", "/dɪˌpriː.ʃiˈeɪ.ʃən/", "topic_market"),
    ("appreciation", "noun", "/əˌpriː.ʃiˈeɪ.ʃən/", "topic_market"),
    ("liquidity", "noun", "/lɪˈkwɪd.ɪ.ti/", "topic_market"),
    ("volatility", "noun", "/ˌvɒl.əˈtɪl.ɪ.ti/", "topic_market"),
    # topic_restaurant
    ("gastronomy", "noun", "/ɡæsˈtrɒn.ə.mi/", "topic_restaurant"),
    ("culinary", "adjective", "/ˈkʌl.ɪ.nər.i/", "topic_restaurant"),
    ("epicurean", "adjective", "/ˌep.ɪˈkjʊər.i.ən/", "topic_restaurant"),
    ("delicacy", "noun", "/ˈdel.ɪ.kə.si/", "topic_restaurant"),
    ("connoisseur", "noun", "/ˌkɒn.ɪˈsɜːr/", "topic_restaurant"),
    ("palate", "noun", "/ˈpæl.ɪt/", "topic_restaurant"),
    ("bouquet", "noun", "/buːˈkeɪ/", "topic_restaurant"),
    ("degustation", "noun", "/ˌdeɡ.ʌˈsteɪ.ʃən/", "topic_restaurant"),
    ("provenance", "noun", "/ˈprɒv.ɪ.nəns/", "topic_restaurant"),
    ("fermentation", "noun", "/ˌfɜː.menˈteɪ.ʃən/", "topic_restaurant"),
    # topic_travel
    ("geopolitical", "adjective", "/ˌdʒiː.əʊ.pəˈlɪt.ɪ.kəl/", "topic_travel"),
    ("sovereignty", "noun", "/ˈsɒv.rɪn.ti/", "topic_travel"),
    ("diaspora", "noun", "/daɪˈæs.pər.ə/", "topic_travel"),
    ("globalisation", "noun", "/ˌɡləʊ.bəl.aɪˈzeɪ.ʃən/", "topic_travel"),
    ("pilgrimage", "noun", "/ˈpɪl.ɡrɪ.mɪdʒ/", "topic_travel"),
    ("nomadic", "adjective", "/nəʊˈmæd.ɪk/", "topic_travel"),
    ("cosmopolitan", "adjective", "/ˌkɒz.məˈpɒl.ɪ.tən/", "topic_travel"),
    ("indigenous", "adjective", "/ɪnˈdɪdʒ.ɪ.nəs/", "topic_travel"),
    ("repatriation", "noun", "/riːˌpæt.riˈeɪ.ʃən/", "topic_travel"),
    ("emigration", "noun", "/ˌem.ɪˈɡreɪ.ʃən/", "topic_travel"),
    # topic_phone
    ("cybersecurity", "noun", "/ˌsaɪ.bə.sɪˈkjʊər.ɪ.ti/", "topic_phone"),
    ("phishing", "noun", "/ˈfɪʃ.ɪŋ/", "topic_phone"),
    ("malware", "noun", "/ˈmæl.weər/", "topic_phone"),
    ("authentication", "noun", "/ɔːˌθen.tɪˈkeɪ.ʃən/", "topic_phone"),
    ("cryptography", "noun", "/krɪpˈtɒɡ.rə.fi/", "topic_phone"),
    ("firewall", "noun", "/ˈfaɪər.wɔːl/", "topic_phone"),
    ("surveillance", "noun", "/səˈveɪ.ləns/", "topic_phone"),
    ("anonymity", "noun", "/ˌæn.əˈnɪm.ɪ.ti/", "topic_phone"),
    ("transparency", "noun", "/trænsˈpær.ən.si/", "topic_phone"),
    ("accountability", "noun", "/əˌkaʊn.təˈbɪl.ɪ.ti/", "topic_phone"),
    # topic_health
    ("aetiology", "noun", "/ˌiː.ti.ˈɒl.ə.dʒi/", "topic_health"),
    ("epidemiology", "noun", "/ˌep.ɪˌdiː.miˈɒl.ə.dʒi/", "topic_health"),
    ("pharmacology", "noun", "/ˌfɑː.məˈkɒl.ə.dʒi/", "topic_health"),
    ("oncology", "noun", "/ɒŋˈkɒl.ə.dʒi/", "topic_health"),
    ("haematology", "noun", "/ˌhiː.məˈtɒl.ə.dʒi/", "topic_health"),
    ("immunology", "noun", "/ˌɪm.jʊˈnɒl.ə.dʒi/", "topic_health"),
    ("endocrinology", "noun", "/ˌen.dəʊ.krɪˈnɒl.ə.dʒi/", "topic_health"),
    ("gastroenterology", "noun", "/ˌɡæs.trəʊˌen.tərˈɒl.ə.dʒi/", "topic_health"),
    ("dermatology", "noun", "/ˌdɜː.məˈtɒl.ə.dʒi/", "topic_health"),
    ("psychiatry", "noun", "/saɪˈkaɪ.ə.tri/", "topic_health"),
    # topic_social
    ("phenomenological", "adjective", "/fɪˌnɒm.ɪ.nəˈlɒdʒ.ɪ.kəl/", "topic_social"),
    ("anthropological", "adjective", "/ˌæn.θrə.pəˈlɒdʒ.ɪ.kəl/", "topic_social"),
    ("sociological", "adjective", "/ˌsəʊ.si.əˈlɒdʒ.ɪ.kəl/", "topic_social"),
    ("philosophical", "adjective", "/ˌfɪl.əˈsɒf.ɪ.kəl/", "topic_social"),
    ("epistemological", "adjective", "/ɪˌpɪs.tɪ.məˈlɒdʒ.ɪ.kəl/", "topic_social"),
    ("postmodernist", "adjective", "/ˌpəʊst.ˈmɒd.ən.ɪst/", "topic_social"),
    ("deconstructionist", "adjective", "/ˌdiː.kənˈstrʌk.ʃən.ɪst/", "topic_social"),
    ("intersectionality", "noun", "/ˌɪn.tə.sek.ʃəˈnæl.ɪ.ti/", "topic_social"),
    ("hegemony", "noun", "/hɪˈdʒem.ə.ni/", "topic_social"),
    ("juxtaposition", "noun", "/ˌdʒʌk.stə.pəˈzɪʃ.ən/", "topic_social"),
],
}


def main():
    print("=" * 60)
    print("TinySteps — Vocabulary Batch 2 Top-Up")
    print("=" * 60)

    existing: dict[str, list] = {}
    global_seen: set[str] = set()

    for level in LEVELS:
        path = os.path.join(VOCAB_DIR, f"{level}.json")
        data = json.load(open(path, encoding="utf-8"))
        existing[level] = data["words"]
        for w in data["words"]:
            global_seen.add(w["word"].lower())

    print(f"Current words: {sum(len(v) for v in existing.values())}")

    for level in LEVELS:
        target = TARGETS[level]
        current = len(existing[level])
        gap = target - current
        if gap <= 0:
            print(f"{level}: full ({current}/{target}), skipping.")
            continue

        pool = BATCH2.get(level, [])
        added = []
        for entry in pool:
            if len(added) >= gap:
                break
            word, pos, ipa, topic = entry
            key = word.lower()
            if key in global_seen:
                continue
            idx = current + len(added) + 1
            added.append({
                "id":               f"{level}_vocab_{idx:03d}",
                "word":             word,
                "ipa":              ipa,
                "pos":              pos,
                "topic_ids":        [topic],
                "example_sentence": make_example(word, pos, level),
                "image_hint":       make_hint(word, pos),
                "frequency_rank":   idx,
            })
            global_seen.add(key)

        merged = existing[level] + added
        for i, w in enumerate(merged, 1):
            w["id"] = f"{level}_vocab_{i:03d}"

        payload = {"level": level, "total_words": len(merged), "words": merged}
        path = os.path.join(VOCAB_DIR, f"{level}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)

        remaining = max(0, target - len(merged))
        flag = "✓" if remaining == 0 else f"⚠ still need +{remaining}"
        print(f"{level}: +{len(added)} → {len(merged)}/{target}  {flag}")

    print("\nDone.")


if __name__ == "__main__":
    main()
