import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["**/__tests__/**/*.test.ts"],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
      // Mirrors tsconfig's "@data/*" -> "./.content/*". Generated by prepare-content,
      // which the pretest hook runs, so content-backed modules are testable.
      "@data": path.resolve(__dirname, ".content"),
      // See test/server-only-stub.ts for why this alias exists.
      "server-only": path.resolve(__dirname, "test/server-only-stub.ts"),
    },
  },
});
